highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://ktmai.github.io
author: Kimberly Mai

# edit this section with your information
# jekyllt.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /
title: Kimberly Mai
name: Kimberly Mai
email: kimberly.mai@ucl.ac.uk
email_full: mailto:kimberly.mai@ucl.ac.uk
website: ktmai.github.io
website_full: https://ktmai.github.io
github: ktmai
twitter: kimberlytmai
linkedin: kimberlytontran
google_scholar: https://scholar.google.com/citations?user=sw26nYwAAAAJ

# needed for travis-ci build
exclude: [vendor]
